branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - main
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - prepareCmd: |
        yq '.version = env(nextRelease.version)' -i Chart.yaml
      generateNotesCmd: |
        git log --format='%B%n===' $(git describe --tags --abbrev=0)..HEAD | head -n -1 | conventional-commits-parser '===' | yq e '.[] | select(.subject == "ReleaseOf*")' -j - | jq -r '. | .subject as $subj  | .body |= sub("(?<a>## \\[)[0-9]+.[0-9]+.[0-9]+(?<b>\\].*)"; "\(.a)"+$subj+"\(.b)") | .body' | sed 's/ReleaseOf //g' | sed 's/##/###/g'
      successCmd: |
        echo "success"
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - assets:
        - Chart.yaml
      message: |-
        chore(release): ${nextRelease.version}

        ${nextRelease.notes}
