apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ms-demo.fullname" . }}
  labels:
    {{- include "ms-demo.labels" . | nindent 4 }}
data:
    DB_HOST: ms-demo-database
    DB_DATABASE: {{ .Values.database.auth.database }}