apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ms-demo.fullname" . }}
  labels:
    {{- include "ms-demo.labels" . | nindent 4 }}
stringData:
  DB_USERNAME: {{ .Values.database.auth.username }}
  DB_PASSWORD: {{ .Values.database.auth.password }}